#!/usr/bin/env bash
# Generate ansible/inventory.ini from the Terraform outputs so host IPs and ECR
# URLs never have to be copied by hand.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
tf_dir="${here}/../terraform"

out="$(terraform -chdir="${tf_dir}" output -json)"

jq_val() { echo "${out}" | python3 -c "import sys,json;print(json.load(sys.stdin)${1})"; }

front_ip="$(jq_val "['frontend_public_ip']['value']")"
back_ip="$(jq_val "['backend_public_ip']['value']")"
back_priv="$(jq_val "['backend_private_ip']['value']")"
ssm_prefix="$(jq_val "['db_ssm_prefix']['value']")"
ecr_front="$(jq_val "['ecr_repository_urls']['value']['frontend']")"
ecr_back="$(jq_val "['ecr_repository_urls']['value']['backend']")"

registry="${ecr_front%%/*}"           # ACCOUNT.dkr.ecr.REGION.amazonaws.com
region="$(echo "${registry}" | cut -d. -f4)"

cat > "${here}/inventory.ini" <<EOF
# Generated by generate-inventory.sh from Terraform outputs. Do not edit by hand.

[frontend]
frontend_node ansible_host=${front_ip}

[backend]
backend_node ansible_host=${back_ip}

[all:vars]
project=pomodoro
aws_region=${region}
ecr_registry=${registry}
ecr_frontend=${ecr_front}
ecr_backend=${ecr_back}
backend_private_ip=${back_priv}
db_ssm_prefix=${ssm_prefix}
EOF

echo "Wrote ${here}/inventory.ini"
